Refactor: point of sale service
GEWIS/sudosos-backend pull request #203
Opened 2024-07-07 14:08 UTC by JustSamuel

# Description
Same story as the container and product service.

## Related issues/external references
#153 

## Types of changes
- Bug fix _(non-breaking change which fixes an issue)_

2024-07-07 21:05 UTC, Yoronex requested changes

2024-07-07 21:05 UTC, Yoronex commented on src/service/product-service.ts
> +  private static  revisionSubQuery(revision?: number): string {
Two spaces :(

2024-07-07 21:05 UTC, Yoronex commented on test/unit/service/point-of-sale-service.ts
> +      const response = (await PointOfSaleService.updatePointOfSale(update)) as PointOfSaleWithContainersResponse;
I think the update function should have a default response (with or without containers/products) such that the responses are also always consistent.

2024-07-08 18:51 UTC, JustSamuel commented on src/service/product-service.ts
> +// TODO figure out why this is unused
Nah, it is just never used, as in: nowhere does a controller expose the ability to use the filter params. However fixing this is outside the scope of this PR. 

I have updated the TODO.

2024-07-09 08:14 UTC, Yoronex approved these changes

2024-07-09 08:14 UTC, Yoronex commented on src/service/point-of-sale-service.ts
> +  public static async updatePointOfSale(update: UpdatePointOfSaleParams) {
This function still has an `|` in its return type (`PointOfSaleResponse` or `PointOfSaleWithContainersResponse`). Please make explicit which type is returned, as this does not seem to be a choice for the user.

2024-07-09 13:38 UTC, merged