Docs: implemented typedoc + vitepress documentation
GEWIS/sudosos-backend pull request #333
Opened 2024-09-25 07:28 UTC by JustSamuel

# Description
This PR does not add any documentation  by itself, apart from a single page on how the documentation works. The main goal of this PR is to create the base template / structure for creating a documentation site which is automatically deployed. 

## Related issues/external references
#285 

## Types of changes
- Documentation improvement

2024-09-25 17:26 UTC, Yoronex requested changes
I absolutely hated reviewing this PR... I spent more than 20 minutes on it, but at least 80% of all my comments were simple typos or errors you could have easily found yourself. I even skipped commenting on every documentation page text that could do with improvement, like in `src/database/schema.ts`. So for the next time, please take some time to review your own PRs, so you can save the other some time...

2024-09-25 17:26 UTC, Yoronex commented on src/controller/debtor-controller.ts
> + */
Two definitions

2024-09-25 17:26 UTC, Yoronex commented on src/controller/event-shift-controller.ts
> + * This is the module page of event-controller.
This is the `event-shift-controller`?

2024-09-25 17:26 UTC, Yoronex commented on src/controller/response/debtor-response.ts
> + */
Wow three times? Damn

2024-09-25 17:26 UTC, Yoronex commented on src/controller/response/dinero-response.ts
> + */
Twice

2024-09-25 17:26 UTC, Yoronex commented on src/controller/response/event-response.ts
> + */
Twice

2024-09-25 17:26 UTC, Yoronex commented on src/controller/response/financial-mutation-response.ts
> + * TODO change
TODO

2024-09-25 17:26 UTC, Yoronex commented on src/controller/response/update-key-response.ts
> + * @module internal/controllers
If you would have checked the contents of this file, you would have seen this response is used only in the `user-controller` when requesting a new API key. So either `users` or `authentication`.

2024-09-25 17:26 UTC, Yoronex commented on src/controller/user-controller.ts
> + */
Twice

2024-09-25 17:26 UTC, Yoronex commented on src/cron.ts
> + * This is the module page the cron job.
Nice inglish

2024-09-25 17:26 UTC, Yoronex commented on package.json
> +    "typedoc": "^0.26.7",
It seems we only use `typedoc` in development environments and never in production environments, so maybe move it to the dev dependencies?

2024-09-26 07:07 UTC, JustSamuel commented
> I absolutely hated reviewing this PR... I spent more than 20 minutes on it, but at least 80% of all my comments were simple typos or errors you could have easily found yourself. I even skipped commenting on every documentation page text that could do with improvement, like in src/database/schema.ts. So for the next time, please take some time to review your own PRs, so you can save the other some time...

I really tried to align all the modules, but given that it were around 400 pages it does not sruprise me that it didn't went as smooth. I mainly focused on the non-internal tags I have to admit.

2024-09-27 15:30 UTC, JustSamuel commented on package.json
> +    "typedoc": "typedoc",
pre<x> is called before <x>, this allows for just typedoc gen

2024-09-27 15:47 UTC, JustSamuel commented on src/gewis/gewis.ts
> + * @mergeTarget
Set which module text will be displayed, in general, all other module text will be ignored as there is only one module. 

The module is the "category"  and the one with @mergeTarget is the category description page.

2024-09-28 14:48 UTC, Yoronex requested changes

2024-09-28 14:48 UTC, Yoronex commented on src/controller/event-shift-controller.ts
> + * This is the module page of event-controller.
Bruh

2024-09-28 16:37 UTC, Yoronex approved these changes

2024-09-28 17:05 UTC, merged