Fixed Transaction Mapping and Sellers bugs
GEWIS/sudosos-backend pull request #38
Opened 2023-06-28 18:25 UTC by JustSamuel

- Bug where credit invoice entries contained products from SubTransactions with different sellers

- Bug where transaction report reported products being sold from subTransactions from different sellers.

2023-06-29 12:06 UTC, Yoronex requested changes

2023-07-11 12:36 UTC, CodeNamedRobin requested changes

2023-07-11 12:36 UTC, CodeNamedRobin commented on src/controller/request/invoice-request.ts
> - * @property {string} description.required - The description of the invoice.
Wrong string.

2023-07-11 12:36 UTC, CodeNamedRobin commented on src/controller/request/invoice-request.ts
First changed string should be unchanged.

2023-07-11 12:36 UTC, CodeNamedRobin commented on test/unit/service/invoice-service.ts
Is correct, but I smell a ESLint fixer being used so Samuel gets to trek a bak.

2023-07-20 13:33 UTC, CodeNamedRobin approved these changes
LGTM!

2023-07-21 23:33 UTC, merged