Add optional nicknames to users
GEWIS/sudosos-backend pull request #43
Opened 2023-08-12 15:41 UTC by Yoronex

Title speaks for itself

2023-08-12 15:58 UTC, CodeNamedRobin commented on test/unit/controller/user-controller.ts
I smell a lint-fix. Rietbak gripel @Yoronex?

2023-08-12 16:01 UTC, CodeNamedRobin requested changes
Only requested change is that I need to see a transaction for 2 kruidige tripel for Roy Kakkenberg in SudoSOS.

2023-08-13 10:19 UTC, JustSamuel requested changes
Ik mis wel dat je nu niet kan zoeken op nickname, wat wel imho een deel van het punt is? Iig moeten we het nog even hebben over hoe we zoeken aanpassen want nu zouden we dus nog meer zooi moeten toevoegen aan de search op user query. Ik ben nogsteeds van mening dat we het beste er van uit kunnen gaan dat we Mysql gebruiken en een fallback query maken voor als het niet zo blijkt te zijn.

2023-08-13 16:53 UTC, Yoronex commented on test/unit/controller/user-controller.ts
This is a lint-fix on develop. Try it yourself. So therefore you should do a rietbak tripel

2023-08-13 17:17 UTC, JustSamuel approved these changes
lftm after changes

2023-08-16 13:11 UTC, JustSamuel approved these changes
mooi?

2023-08-16 13:54 UTC, merged