Update user-debt-notification.ts
GEWIS/sudosos-backend pull request #98
Opened 2023-10-20 09:26 UTC by WdeBondt

Added actual link to sudosos website in debt notification

2023-10-23 05:24 UTC, Yoronex commented
Please use the environment variable `URL` instead of hardcoding the url. You can do this by using the `context.url` variable.

2023-10-23 05:25 UTC, Yoronex requested changes

2023-10-23 05:25 UTC, Yoronex commented on src/mailer/templates/user-debt-notification.ts
> +Go to the  <a href="https://sudosos.gewis.nl">SudoSOS website</a> to deposit money into your account. With this you prevent getting fined into the future.
Please use the environment variable `URL` instead of hardcoding the url. You can do this by using the `context.url` variable.

2023-10-23 05:25 UTC, Yoronex commented on src/mailer/templates/user-debt-notification.ts
> +Ga snel naar de SudoSOS website(https://sudosos.gewis.nl) om je saldo op te hogen! Zo voorkom je dat je een boete krijgt.
Please use the environment variable `URL` instead of hardcoding the url. You can do this by using the `context.url` variable.

2024-05-22 17:05 UTC, closed without merging

2024-05-22 17:05 UTC, SuperVK commented
Decided not to do this (in multiple ABC meeting) because of spam scores (You do not want "Pay via this link" links in our mails because scams)